### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by ZimoLoveShuang** [nonepage/auto-submit#1]
一些疑问：
1. 为什么你fork我的项目，而我却看不到fork的记录
![image](https://user-images.githubusercontent.com/32027313/80297817-5439e000-87b9-11ea-93b5-a1742afe3d1e.png)
2. 为什么你参考了项目，而没有给我的项目点star
![image](https://user-images.githubusercontent.com/32027313/80297860-aed33c00-87b9-11ea-8419-8a4720329f29.png)

**Comment by nonepage** [comment]
fork过来,提交上去版本内有个人信息,但是不太懂这个github怎么弄,所以删库,pycharm新提交上来开了库,所以没有你的fork信息,所以在文档页面注明了你的项目地址和开发者信息,star这个给你点了嗷,每太关心这些,sorry~

**Comment by ZimoLoveShuang** [comment]
> fork过来,提交上去版本内有个人信息,但是不太懂这个github怎么弄,所以删库,pycharm新提交上来开了库,所以没有你的fork信息,所以在文档页面注明了你的项目地址和开发者信息,star这个给你点了嗷,每太关心这些,sorry~

原来是这样的操作，我就说很奇怪，怎么会fork的我都看不到，没在意这些，只是今天推荐在旁边我看到了这个仓库，感觉奇怪，就问一下
